// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package dto

import (
	"github.com/aereal/smarate/api/model"
)

type FighterFightResultConnection struct {
	Nodes           []*model.FighterFightResult `json:"nodes"`
	WinRatio        float64                     `json:"winRatio"`
	MostWonFighters *MatchupConnection          `json:"mostWonFighters"`
}

type GlobalFightResultConnection struct {
	Nodes []*model.GlobalFightResult `json:"nodes"`
}

type Matchup struct {
	RivalFighter *model.Fighter `json:"rivalFighter"`
	WinRatio     float64        `json:"winRatio"`
}

type MatchupConnection struct {
	Nodes []*Matchup `json:"nodes"`
}

type User struct {
	ID           string                     `json:"id"`
	Preference   *UserPreference            `json:"preference"`
	FightResults *UserFightResultConnection `json:"fightResults"`
}

type UserFightResult struct {
	MyFighter    *model.Fighter `json:"myFighter"`
	RivalFighter *model.Fighter `json:"rivalFighter"`
	Won          bool           `json:"won"`
}

type UserFightResultConnection struct {
	Nodes []*UserFightResult `json:"nodes"`
}

type UserPreference struct {
	DefaultFighterID int `json:"defaultFighterID"`
}
