// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package dto

import (
	"github.com/aereal/smarate/api/model"
)

type GlobalFightResultConnection struct {
	Nodes []*model.GlobalFightResult `json:"nodes"`
}

type MatchupConnection struct {
	Nodes []*model.Matchup `json:"nodes"`
}

type UserFightResultConnection struct {
	Nodes []*model.UserFightResult `json:"nodes"`
}
