// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"context"
	"github.com/aereal/smarate/api/auth"
	"github.com/aereal/smarate/api/gql"
	"github.com/aereal/smarate/api/gql/resolvers"
	"github.com/aereal/smarate/api/repo"
	"github.com/aereal/smarate/api/web"
)

// Injectors from wire.go:

func InitializeWeb(ctx context.Context) (*web.Web, error) {
	app, err := ProvideFirebaseApp(ctx)
	if err != nil {
		return nil, err
	}
	client, err := ProvideFirestoreClient(ctx, app)
	if err != nil {
		return nil, err
	}
	repoRepo := repo.ProvideRepo(client)
	resolver := resolvers.ProvideResolver(repoRepo)
	executableSchema := gql.ProvideExecutableSchema(resolver)
	middleware := auth.ProvideMiddleware(app)
	webWeb := web.ProvideWeb(executableSchema, client, middleware)
	return webWeb, nil
}
